<a href="https://colab.research.google.com/github/Francisco-Italo/ml2023-Italo-Moraes/blob/master/Atividades/01-Pre-processamento_Limpeza_Analise_de_Dados/04_Lidando_com_atributos_categ%C3%B3ricos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 4 - Lidando com atributos categóricos

# *Features* nominais e ordinais
## **Nominal:** aquilo cujo rótulo do dado é um texto
## **Ordinal:** representação numeral do dado

In [ ]:
import pandas as pd

labels = ['polo #1','polo #2','polo #3']

df = pd.DataFrame([['verde', 'M', 10.1, 'classe2'],
                   ['vermelho', 'G', 13.5, 'classe1'],
                   ['azul', 'XG', 15.3, 'classe2']],
                  index=labels, columns=['cor', 'tamanho', 'preco', 'rotulo_classe'])

df

              cor tamanho  preco rotulo_classe
polo #1     verde       M   10.1       classe2
polo #2  vermelho       G   13.5       classe1
polo #3      azul      XG   15.3       classe2

## Mapeando *features* ordinais

In [ ]:
# chave:valor -> Associação de um valor a uma chave, podendo ser de qualquer tipo
size_mapping = {'XG': 3,
                'G': 2,
                'M': 1}
# Substituição da chave pelo valor associado
df['tamanho'] = df['tamanho'].map(size_mapping)
df

              cor  tamanho  preco rotulo_classe
polo #1     verde        1   10.1       classe2
polo #2  vermelho        2   13.5       classe1
polo #3      azul        3   15.3       classe2

In [ ]:
# Aplica o inverso do que foi feito anteriormente (substitui o valor pela chave associada)
inv_size_mapping = {v: k for k, v in size_mapping.items()}
df['tamanho'].map(inv_size_mapping)

polo #1     M
polo #2     G
polo #3    XG
Name: tamanho, dtype: object

## Codificando rótulos de classe

In [ ]:
import numpy as np

# Criando um dicionario para converter rótulos de classe de strings para inteiros
class_mapping = {label: idx for idx, label in enumerate(np.unique(df['rotulo_classe']))}
class_mapping

{'classe1': 0, 'classe2': 1}

In [ ]:
# Conversão de labels do texto para o índice numérico
df['rotulo_classe'] = df['rotulo_classe'].map(class_mapping)
df

              cor  tamanho  preco  rotulo_classe
polo #1     verde        1   10.1              1
polo #2  vermelho        2   13.5              0
polo #3      azul        3   15.3              1

In [ ]:
# Mapeamento reverso do rótulo de classes
inv_class_mapping = {v: k for k, v in class_mapping.items()}
df['rotulo_classe'] = df['rotulo_classe'].map(inv_class_mapping)
df

              cor  tamanho  preco rotulo_classe
polo #1     verde        1   10.1       classe2
polo #2  vermelho        2   13.5       classe1
polo #3      azul        3   15.3       classe2